version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s [%(name)s] [%(levelname)s] :%(levelno)s: %(message)s"
    error:
        format: "%(asctime)s [%(name)s] [%(levelname)s] :%(levelno)s: %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://flask.logging.wsgi_errors_stream
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: ./logs/info.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: ./logs/errors.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
root:
    level: INFO
    handlers: [console,info_file_handler,error_file_handler]